spring.application.name=SchoolGuard-MVC

# Conexión a la Base de Datos (Variables dinámicas con fallback local)
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/schoolguard}
spring.datasource.username=${DATABASE_USER:root}
spring.datasource.password=${DATABASE_PASSWORD:75126939}
spring.datasource.driver-class-name=${DATABASE_DRIVER:com.mysql.cj.jdbc.Driver}

# JPA / Hibernate
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.MySQLDialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Flyway (deshabilitado - usando ddl-auto)
spring.flyway.enabled=false

# Puerto del servidor (OBLIGATORIO para Render: debe leer la variable PORT)
server.port=${PORT:8080}

spring.main.allow-bean-definition-overriding=true
springdoc.swagger-ui.path=/swagger-ui.html