spring.application.name=agenda-service

# Conexion a la Base de Datos deber ser la misma BD que el MVC principal
spring.datasource.url=jdbc:mysql://localhost:3306/schoolguard
spring.datasource.username=root
spring.datasource.password=75126939
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate crea/actualiza tablas agenda_profesor y horario_semanal
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Flyway deshabilitado usando ddl-auto
spring.flyway.enabled=false

# Puerto del microservicio
# 8080 = MVC,
# 8081 = asistencia,
# 8082 = agenda
server.port=8082

# IMPORTANTE: debe ser la misma clave secreta que usa el MVC principal (SchoolGuard)
jwt.secret=${JWT_SECRET:SchoolGuardSecretKeyMuySeguraParaJWT2024XYZ!}

spring.main.allow-bean-definition-overriding=true
springdoc.swagger-ui.path=/swagger-ui.html